*8
   PRINT 'PREISELASTIZITAET DER NACHFRAGE'
   COMMENT P = PREIS              M = MENGE
   COMMENT A = PUNKTELASTIZITAET-1 BEZOGEN AUF I-1
   COMMENT B = PUNKTELASTIZITAET-2 BEZOGEN AUF I
   COMMENT C = BOGENELASTIZITAET-1 DURCHSCHNITTSWERTBASIS
   COMMENT D = BOGENELASTIZITAET-2 PREISAENDERUNG BEZOGEN AUF NEUEN PREIS,
   COMMENT     MENGENAENDERUNG BEZOGEN AUF AUSGANGSMENGE
   COMMENT E = BOGENELASTIZITAET-3 PREISAENDERUNG BEZOGEN AUF AUSGANGSPREIS,
   COMMENT     MENGENAENDERUNG BEZOGEN AUF NEUE MENGE
   COMMENT F = BOGENELASTIZITAET AUF LOGERITHMISCHER 21S9S
   COMMENT DIMENSIONIERUNG DER VEKTOREN
   DIM P(100),M(100)
   COMMENT N = ZAHL DER EINGELESENEN WERTE
10 READ N
   IF N$='ENDE' GOTO 20
   PRINT
   PRINT
   PRINT '     PREIS','     MENGE','      PUNKT-','      PUNKT-','      BOGEN-',
   PRINT '      BOGEN-','      BOGEN-','      BOGEN-'
   PRINT ' ',' ',' ELASTIZITAET-1',' ELASITZITAET-2',' ELASTIZITAET-1',
   PRINT ' ELASTIZITAET-2',' ELASTIZITAET-3',' ELASTIZITAET-4'
   PRINT
   COMMENT EINLESEN DER P- UND M-WERTE
   FOR I = 1 TO N
     READ P(I),M(I)
   NEXT I
   COMMENT ELASTIZITAETSBERECHNUNG
   PRINT P(1),M(1),'AUSGANGSPUNKT'
   FOR I=2 TO N
11   LET A=(M(I-1)-M(I))/M(I-1)*P(I-1)/(P(I-1)-P(I))
12   LET B=(M(I-1)-M(I))/M(I)*P(I)/(P(I-1)-P(I))
13   LET C=(M(I-1)-M(I))/(M(I-1)+M(I))*(P(I-1)+P(I))/(P(I-1)-P(I))
14   LET D=P(I)/M(I-1)*(M(I-1)-M(I))/(P(I-1)-P(I))
15   LET E=P(I-1)/M(I)*(M(I-1)-M(I))/(P(I-1)-P(I))
16   LET F=(LOG(M(I))-LOG(M(I-1)))/(LOG(P(I))-LOG(P(I-1)))
     COMMENT DRUCK,PREISELASTIZITAET NEGATIV DEFINIERT
     PRINT P(I),M(I),-A,-B,-C,-D,-E,-F
   NEXT I
   GOTO 10
20 STOP
   END LIST DATA
10,134,1,124,2,114,3,104,4,94,5,84,6,74,7,64,8,54,9,44,10
2,12,32,10,40
'ENDE'
*